# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

production:
 PAGSEGURO_URL_NOTIFICATION: 'http://www.umesgo.org.br/payment/notifications'
 PAGSEGURO_URL_CALLBACK: 'http://www.umesgo.org.br/payment/confirmacao'
 PAGSEGURO_TOKEN: '8EA9624D2D454FFD9FF2B48C2E939380'
 PAGSEGURO_EMAIL: 'vinicius.deoliveira@outlook.com'
 PAGSEGURO_ENVIRONMENT: 'sandbox'
 FACEBOOK_APP_ID: '1198153637329055'
 FACEBOOK_APP_SECRET: '9e1921448be84657f36c418ceb7fc355'
 MOBILEAPP_FACEBOOK_APP_ID: ''
 MOBILEAPP_FACEBOOK_APP_SECRET: ''
 STUDENTCASYSTEM_DATABASE_USER: 'rails'
 STUDENTCASYSTEM_DATABASE_PASSWORD: 'asShgiVzlr'
 STUDENTCASYSTEM_EMAIL_USER: 'viniciusdeoliveirasantos@gmail.com'
 STUDENTCASYSTEM_EMAIL_SMTP: 'smtp.gmail.com'
 STUDENTCASYSTEM_EMAIL_PORT: '587'
 STUDENTCASYSTEM_EMAIL_DOMAIN: 'gmail.com'
 STUDENTCASYSTEM_EMAIL_PASSWORD: '1820goiania'
 STUDENTCASYSTEM_EMAIL_SITE_DOMAIN: 'http://www.umesgo.org.br'
 STUDENTCASYSTEM_EMAIL_FORM_RECEIVER: 'viniciusdeoliveirasantos@gmail.com'
 STUDENTCASYSTEM_API_USERNAME: 'adminuser'
 STUDENTCASYSTEM_API_PASSWORD: '454c430be6c1d29313bb0d313e5a9986'
 STUDENTCASYSTEM_NOME_ENTIDADE: 'UMESGO'
 STUDENTCASYSTEM_LOGO_ENTIDADE: 'logo.png'
 RECAPTCHA_PUBLIC_KEY:  '6LfleBIUAAAAAEKFcsNzMELPMp7cDM1WnfzmFnOt'
 RECAPTCHA_PRIVATE_KEY: '6LfleBIUAAAAAKzU5t3BnhX4nu-sQfJXk0-lTYFb'
 AMAZON_S3_BUCKET: 'umesgo'
 AMAZON_S3_ACCESS_KEY_ID: 'AKIAIFHIN4UL5LTDNZTQ'
 AMAZON_S3_SECRET_ACCESS_KEY_ID: 'mVB9lF0OiF4YShNtzV7J9dW59rXcHKQKhc3t1Q3P'
 AMAZON_S3_REGION: 'sa-east-1'

development:
 PAGSEGURO_URL_NOTIFICATION: 'http://localhost:3000/payment/notifications'
 PAGSEGURO_URL_CALLBACK: 'http://localhost:3000/payment/confirmacao'
 PAGSEGURO_TOKEN: '8EA9624D2D454FFD9FF2B48C2E939380'
 PAGSEGURO_EMAIL: 'vinicius.deoliveira@outlook.com'
 PAGSEGURO_ENVIRONMENT: 'sandbox'
 FACEBOOK_APP_ID: '198158320661920'
 FACEBOOK_APP_SECRET: '06aa7b6d516e9198c7d18fc975dbd8f7'
 STUDENTCASYSTEM_DATABASE_USER: 'postgres'
 STUDENTCASYSTEM_DATABASE_PASSWORD: 'vinte3cinco'
 STUDENTCASYSTEM_EMAIL_USER: 'viniciusdeoliveirasantos@gmail.com'
 STUDENTCASYSTEM_EMAIL_SMTP: 'smtp.gmail.com'
 STUDENTCASYSTEM_EMAIL_PORT: '587'
 STUDENTCASYSTEM_EMAIL_DOMAIN: 'gmail.com'
 STUDENTCASYSTEM_EMAIL_SITE_DOMAIN: 'localhost:3000'
 STUDENTCASYSTEM_EMAIL_FORM_RECEIVER: 'viniciusdeoliveirasantos@gmail.com'
 STUDENTCASYSTEM_EMAIL_PASSWORD: '1820goiania'
 STUDENTCASYSTEM_API_USERNAME: 'adminuser'
 STUDENTCASYSTEM_API_PASSWORD: 'c430b1d23b6cd314543e5931a998b0e6'
 STUDENTCASYSTEM_NOME_ENTIDADE: 'Nome Entidade'
 STUDENTCASYSTEM_LOGO_ENTIDADE: 'logo.png'
 RECAPTCHA_PUBLIC_KEY:  '6LcajicTAAAAAP23pEpr8R7kxVnxIFMiSFrP7vxK'
 RECAPTCHA_PRIVATE_KEY: '6LcajicTAAAAALK8MsZ8z0XYSXxAuTFNb6c719o9'
 AMAZON_S3_BUCKET: 'studentcasystem'
 AMAZON_S3_ACCESS_KEY_ID: 'AKIAIUSAKLAQKMHRDR7A'
 AMAZON_S3_SECRET_ACCESS_KEY_ID: ''
 AMAZON_S3_REGION: 'sa-east-1'

test:
 PAGSEGURO_URL_NOTIFICATION: 'http://localhost:3000/payment/notifications'
 PAGSEGURO_URL_CALLBACK: 'http://localhost:3000/estudantes'
 PAGSEGURO_TOKEN: '8EA9624D2D454FFD9FF2B48C2E939380'
 PAGSEGURO_EMAIL: 'vinicius.deoliveira@outlook.com'
 PAGSEGURO_ENVIRONMENT: 'sandbox'
 FACEBOOK_APP_ID: '151222168574628'
 FACEBOOK_APP_SECRET: '8e8fc5dc970a82cb437f49811c039044'
 STUDENTCASYSTEM_DATABASE_USER: 'studentcasystem'
 STUDENTCASYSTEM_DATABASE_PASSWORD: 'studentcasystem'
 STUDENTCASYSTEM_EMAIL_USER: 'viniciusdeoliveirasantos@gmail.com'
 STUDENTCASYSTEM_EMAIL_SMTP: 'smtp.gmail.com'
 STUDENTCASYSTEM_EMAIL_PORT: '587'
 STUDENTCASYSTEM_EMAIL_DOMAIN: 'gmail.com'
 STUDENTCASYSTEM_EMAIL_SITE_DOMAIN: 'localhost:3000'
 STUDENTCASYSTEM_EMAIL_FORM_RECEIVER: 'viniciusdeoliveirasantos@gmail.com'
 STUDENTCASYSTEM_EMAIL_PASSWORD: '1820goiania'
 STUDENTCASYSTEM_API_USERNAME: 'adminuser'
 STUDENTCASYSTEM_API_PASSWORD: 'c430b1d23b6cd314543e5931a998b0e6'
 STUDENTCASYSTEM_NOME_ENTIDADE: 'Nome Entidade'
 STUDENTCASYSTEM_LOGO_ENTIDADE: 'logo.png'
 RECAPTCHA_PUBLIC_KEY:  '6LcajicTAAAAAP23pEpr8R7kxVnxIFMiSFrP7vxK'
 RECAPTCHA_PRIVATE_KEY: '6LcajicTAAAAALK8MsZ8z0XYSXxAuTFNb6c719o9'
 AMAZON_S3_BUCKET: 'studentcasystem'
 AMAZON_S3_ACCESS_KEY_ID: ''
 AMAZON_S3_SECRET_ACCESS_KEY_ID: ''
 AMAZON_S3_REGION: 'sa-east-1'